# Generated by Django 4.2.3 on 2023-07-30 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='author',
            new_name='user',
        ),
    ]
