# Generated by Django 4.2.3 on 2023-07-30 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_rename_user_journal_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='emotion_predications',
            field=models.IntegerField(default=0),
        ),
    ]
