# Generated by Django 4.2.3 on 2023-08-10 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_journal_emotion_predications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'ordering': ('-created_at',), 'verbose_name': 'Journal', 'verbose_name_plural': 'Journals'},
        ),
    ]
