# Generated by Django 4.2.3 on 2023-07-30 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0006_alter_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='emotion_predications',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='emotions',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
