# Generated by Django 4.2.3 on 2023-08-10 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0007_post_emotion_predications_post_emotions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
