# Generated by Django 4.2.3 on 2023-08-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfHelp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='library',
            name='link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
